#!/bin/bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source $DIR/../../envs.sh
cd $CUDA_LANE_DETECTION_RUNNING_SCRIPT_FOLDER

[ -f $CUDA_LANE_DETECTION_TIMING_LOGS ] && > $CUDA_LANE_DETECTION_TIMING_LOGS
[ -f $CUDA_LANE_DETECTION_OUTPUT_LOGS ] && > $CUDA_LANE_DETECTION_OUTPUT_LOGS
[ -f $CUDA_LANE_DETECTION_TIMING_PER_INPUT_LOGS ] && > $CUDA_LANE_DETECTION_TIMING_PER_INPUT_LOGS

while [ 1 ]
do
    time ./run.sh > $CUDA_LANE_DETECTION_OUTPUT_LOGS 
    grep "Processing time" $CUDA_LANE_DETECTION_OUTPUT_LOGS >> $CUDA_LANE_DETECTION_TIMING_PER_INPUT_LOGS
    # cat $CUDA_LANE_DETECTION_OUTPUT_LOGS  | grep "Processing time" 
done 2>> $CUDA_LANE_DETECTION_TIMING_LOGS
