version: '3'
services:
  chauffeur.qemu.builder:
    image: arm.chauffeur.qemu.builder
    build: .
    volumes:
      - $PWD/../../cross-apps:/workspace/cross-apps
      - $PWD/../../applications:/workspace/applications
      - $PWD/build.sh:/workspace/build.sh
      - $PWD/keys/trusted-keys:/trusted-keys
      - $PWD/patches:/workspace/applications/patches

# Used for legacy compilation
# - $PWD/../docker/tmp-jetpack-files:/jetpack-files